### PR TITLE
feat(forms)

### PR DESCRIPTION
**Pull request by gerard-kanters**

### CODE REVIEW

**Comment by hypeJunction** [comment]
Could you change the commit message to start with `feat(forms): ` otherwise it won't show in changelog

**Comment by gerard-kanters** [comment]
Done

**Comment by hypeJunction** [comment]
When I say commit message I don't mean the PR title. It's the message you type when you commit the changes. Those commit messages end up in the CHANGELOG.md, so they should make sense.

**Comment by hypeJunction** [comment]
Replaced by #4

**Pull request closed without merging**
